import type { Metadata } from "next"
import { Outfit, MonteCarlo } from "next/font/google"
import "./globals.css"

import Provider from "@/provider"

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
})

const monteCarlo = MonteCarlo({
  variable: "--font-monte-carlo",
  subsets: ["latin"],
  display: "swap",
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfit.variable} ${monteCarlo.variable} antialiased`}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
